name: Deploy to Fly.io

on:
  push:
    branches:
      - main
      - teste

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup FlyCTL
        uses: superfly/flyctl-actions/setup-flyctl@master

      # Deploy da branch main para Produção (usando fly.toml)
      - name: Deploy Produção (main)
        if: github.ref == 'refs/heads/main'
        run: flyctl deploy --remote-only --config fly.toml
        working-directory: ./estoque
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      # Deploy da branch teste para Staging (usando fly.staging.toml)
      - name: Deploy Teste (teste)
        if: github.ref == 'refs/heads/teste'
        run: flyctl deploy --remote-only --config fly.staging.toml
        working-directory: ./estoque
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}